// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_compass = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_compass, &ui_img_compass_png);
    lv_obj_set_width(ui_compass, LV_SIZE_CONTENT);   /// 1072
    lv_obj_set_height(ui_compass, LV_SIZE_CONTENT);    /// 103
    lv_obj_set_x(ui_compass, 0);
    lv_obj_set_y(ui_compass, 0);
    lv_obj_set_align(ui_compass, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_compass, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_compass, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_overlay = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_overlay, &ui_img_overlay_png);
    lv_obj_set_width(ui_overlay, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_overlay, LV_SIZE_CONTENT);    /// 170
    lv_obj_set_align(ui_overlay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_overlay, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_overlay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_indicator = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_indicator, &ui_img_indicator_1_png);
    lv_obj_set_width(ui_indicator, LV_SIZE_CONTENT);   /// 62
    lv_obj_set_height(ui_indicator, LV_SIZE_CONTENT);    /// 17
    lv_obj_set_x(ui_indicator, 0);
    lv_obj_set_y(ui_indicator, 11);
    lv_obj_set_align(ui_indicator, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_indicator, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_indicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 100);
    lv_obj_set_height(ui_Container1, 27);
    lv_obj_set_x(ui_Container1, -65);
    lv_obj_set_y(ui_Container1, -102);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_degree = lv_label_create(ui_Container1);
    lv_obj_set_height(ui_degree, 49);
    lv_obj_set_width(ui_degree, LV_SIZE_CONTENT);   /// 76
    lv_obj_set_align(ui_degree, LV_ALIGN_CENTER);
    lv_label_set_text(ui_degree, "0°");
    lv_obj_set_style_text_color(ui_degree, lv_color_hex(0xFF6918), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_degree, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_degree, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_direction = lv_label_create(ui_Container1);
    lv_obj_set_height(ui_direction, 49);
    lv_obj_set_width(ui_direction, LV_SIZE_CONTENT);   /// 76
    lv_obj_set_x(ui_direction, 3);
    lv_obj_set_y(ui_direction, 0);
    lv_obj_set_align(ui_direction, LV_ALIGN_CENTER);
    lv_label_set_text(ui_direction, "N");
    lv_obj_set_style_text_font(ui_direction, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

}
